services:
  - type: web
    name: tijaniyah-muslim-pro
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tijaniyah-muslim-pro.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
